#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-plexus
Version  : 1.0.10
Release  : 2
URL      : https://github.com/codehaus-plexus/plexus-pom/archive/plexus-1.0.10.tar.gz
Source0  : https://github.com/codehaus-plexus/plexus-pom/archive/plexus-1.0.10.tar.gz
Source1  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.1.12/plexus-components-1.1.12.pom
Source2  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.1.14/plexus-components-1.1.14.pom
Source3  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.1.15/plexus-components-1.1.15.pom
Source4  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.1.17/plexus-components-1.1.17.pom
Source5  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.1.18/plexus-components-1.1.18.pom
Source6  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.1.19/plexus-components-1.1.19.pom
Source7  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.1.20/plexus-components-1.1.20.pom
Source8  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.1.4/plexus-components-1.1.4.pom
Source9  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.1.6/plexus-components-1.1.6.pom
Source10  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.1.9/plexus-components-1.1.9.pom
Source11  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.2/plexus-components-1.2.pom
Source12  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.3.1/plexus-components-1.3.1.pom
Source13  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/4.0/plexus-components-4.0.pom
Source14  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/1.0.10/plexus-1.0.10.pom
Source15  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/1.0.11/plexus-1.0.11.pom
Source16  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/1.0.12/plexus-1.0.12.pom
Source17  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/1.0.4/plexus-1.0.4.pom
Source18  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/1.0.5/plexus-1.0.5.pom
Source19  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/1.0.8/plexus-1.0.8.pom
Source20  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/1.0.9/plexus-1.0.9.pom
Source21  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/2.0.2/plexus-2.0.2.pom
Source22  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/2.0.3/plexus-2.0.3.pom
Source23  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/2.0.5/plexus-2.0.5.pom
Source24  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom
Source25  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/2.0.7/plexus-2.0.7.pom
Source26  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/3.0.1/plexus-3.0.1.pom
Source27  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/3.1/plexus-3.1.pom
Source28  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/3.2/plexus-3.2.pom
Source29  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/3.3.1/plexus-3.3.1.pom
Source30  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/3.3.2/plexus-3.3.2.pom
Source31  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/3.3/plexus-3.3.pom
Source32  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/4.0/plexus-4.0.pom
Source33  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/5.0/plexus-5.0.pom
Source34  : https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/5.1/plexus-5.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-plexus-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-plexus package.
Group: Data

%description data
data components for the mvn-plexus package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.12
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.12

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.14
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.14

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.15
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.15

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.17
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.17

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.18
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.18

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.19
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.19

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.20
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.20

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.4
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.6
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.9
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.2
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.3.1
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.3.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/4.0
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/4.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.10
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.11
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.11

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.12
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.12

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.4
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.5
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.8
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.9
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.2
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.3
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.5
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.6
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.7
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.0.1
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.1
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.2
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.3.1
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.3.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.3.2
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.3.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.3
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/4.0
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/4.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/5.0
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/5.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/5.1
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/5.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.12/plexus-components-1.1.12.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.14/plexus-components-1.1.14.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.15/plexus-components-1.1.15.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.17/plexus-components-1.1.17.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.18/plexus-components-1.1.18.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.19/plexus-components-1.1.19.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.20/plexus-components-1.1.20.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.4/plexus-components-1.1.4.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.6/plexus-components-1.1.6.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.1.9/plexus-components-1.1.9.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.2/plexus-components-1.2.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/1.3.1/plexus-components-1.3.1.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus-components/4.0/plexus-components-4.0.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.10/plexus-1.0.10.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.11/plexus-1.0.11.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.12/plexus-1.0.12.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.4/plexus-1.0.4.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.5/plexus-1.0.5.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.8/plexus-1.0.8.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/1.0.9/plexus-1.0.9.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.2/plexus-2.0.2.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.3/plexus-2.0.3.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.5/plexus-2.0.5.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/2.0.7/plexus-2.0.7.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.0.1/plexus-3.0.1.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.1/plexus-3.1.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.2/plexus-3.2.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.3.1/plexus-3.3.1.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.3.2/plexus-3.3.2.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/3.3/plexus-3.3.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/4.0/plexus-4.0.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/5.0/plexus-5.0.pom
/usr/share/java/.m2/repository/org/codehaus/plexus/plexus/5.1/plexus-5.1.pom
